language: python
python:
  - "3.6"      # current default Python on Travis CI
#  - "nightly"  # nightly build
# command to install dependencies
install:
  - python setup.py install
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - pytest --cov-report xml --cov='./genrl/' --cov-config=.coveragerc
  
after_success:
  - codecov --token=16dca61f-670e-4a9a-bda6-e016cb5579db

jobs:
  include:
    #Run tests
    - stage: Lint Check
      python: "3.6"
      install:
        - pip install black flake8 isort black
      script:
        - flake8 .
        - black --check .
        - isort -rc -c .
      after_success:
        
    - stage: test
      python: "3.6"
      install: 
        - python setup.py install
        - pip install codecov pytest-cov
      script:
        - pytest --cov-report xml --cov='./genrl/' --cov-config=.coveragerc
      
      after_success:
        - codecov --token=16dca61f-670e-4a9a-bda6-e016cb5579db

    # Deploy Documentation
    - stage: Docs
      python: "3.6"
      if: type != cron
      # Use previously defined before_install
      before_install: *before_install

      install:
        - pip install -r docs/requirements.txt

      script:
        - make -C docs/
      after_success: # Nothing to do

      # Deploy built docs : a) when PR is merged to master, b) when a tag is built
      deploy:
        - provider: pages
          edge: true
          token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
          keep_history: false
          local_dir: docs/build/html
          on:
            branch: master
        - provider: pages
          edge: true
          token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
          keep_history: false
          local_dir: docs/build/html
          on:
            tags: true
